name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # 或者 master，根据你的默认分支设置

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/setup-pages@v2

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Deploy GitHub Pages"
        git push origin main
